# Generated by Django 3.2.7 on 2021-09-22 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mymodeladmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModelAdmin',
        ),
    ]
